- name: Install basic packages with Brew
  become: yes
  community.general.homebrew:
    name: "{{ item }}"
  loop: "{{ packages.core }}"

- name: Install Mac-specific packages with Brew
  become: yes
  community.general.homebrew:
    name: "{{ item }}"
  loop: "{{ packages.mac }}"

- name: Install work packages with Brew
  become: yes
  when: is_work
  community.general.homebrew:
    name: "{{ item }}"
  loop: "{{ packages.work }}"
