- name: Install core packages with Pacman
  become: yes
  community.general.pacman:
    name: "{{ item }}"
  loop: "{{ packages.core }}"

- name: Install Arch-specific packages with Pacman
  become: yes
  community.general.pacman:
    name: "{{ item }}"
  loop: "{{ packages.arch }}"

- name: Install WM
  become: yes
  community.general.pacman:
    name: "{{ item }}"
  loop: "{{ packages.wm }}"
